(add-to-list 'load-path "~/.emacs.d/lisp")
(add-to-list 'load-path "~/.emacs.d/themes")
(add-to-list 'load-path "~/.emacs.d/personal/")

(load "setup-defaults")
(load "setup-package")
(load "setup-theme")

(load "setup-auto-complete")
(load "setup-c-mode")
(load "setup-company")
(load "setup-dart-mode")
(load "setup-dash")
(load "setup-dired")
(load "setup-elscreen")
(load "setup-emacs-lisp-mode")
(load "setup-ensime")
;; (load "setup-evil")
(load "setup-fiplr")
(load "setup-flycheck-mode")
(load "setup-go")
(load "setup-haml-mode")
(load "setup-haskell-mode")
(load "setup-helm")
(load "setup-ibuffer")
(load "setup-java")
(load "setup-js2-mode")
(load "setup-markdown-mode")
(load "setup-octave-mode")
(load "setup-omnisharp")
(load "setup-recentf")
(load "setup-rhtml-mode")
(load "setup-ruby-mode")
(load "setup-smooth-scroll")
(load "setup-yaml-mode")

(server-start)
